*** Settings ***
Resource    ${CURDIR}/../keywords/features/help_check_api.resource
Resource    ${CURDIR}/../keywords/features/register_api.resource
Resource    ${CURDIR}/../keywords/features/order_product_api.resource
Resource    ${CURDIR}/../keywords/features/get_order_api.resource
Resource    ${CURDIR}/../keywords/commons/api_commons.resource
Resource    ${CURDIR}/../keywords/commons/commons.resource



